config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  get "/perfil/:id", to: "users#show", as: "profile"

  get "participates/new/:groupid", to: "participates#new", as: "new_participate"
  post "participates/new/:groupid", to: "participates#create", as: "create_participate"
  delete "participates/:id", to: "participates#destroy", as: "leave_group"

  get "exchanges/new/:groupid", to: "exchanges#new", as: "new_exchange"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  get "groups/home"
  get "groups/index"

  get "shops/index"
  get "shops/show"

  resources :users
  resources :groups
  resources :exchanges
  resources :shops
  resources :give

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/group.rb
# Relacion Grupo en el modelo logico
class Group < ApplicationRecord
  validates :name, presence: true
  validates :max_participants_allowed, presence: true
  validates :admin_email, presence: true
  validates :admin_id, presence: true
  belongs_to :admin

  has_many :participates, dependent: :destroy
  has_many :exchanges, dependent: :destroy

  # Retorna true si el grupo tiene espacio para otro participante, false si no
  def has_free_space
    self.participates.count < self.max_participants_allowed
  end

  # Retorna true si el grupo no tiene intercambios pendientes, false si no
  def doesnt_has_pending_exchanges
    Exchange.where(["group_id = ? and exchange_date >= ?", self.id, Time.now])
      .order(exchange_date: :desc)
      .empty?
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :find_group, only: [:show, :edit, :update, :destroy]

  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
    @participants = Participate.where group_id: @group.id
  end

  def new
    @group = Group.new
  end

  def edit
  end

  def create
    @group = Group.new(group_params)

    # Si el usuario existe...
    if User.find_by(email: current_user.email)

      # Y es administrador, entonces buscalo
      if Admin.find_by(email: current_user.email)
        admin = Admin.find_by(email: current_user.email)
        # Si no es administrador, crealo
      else
        admin = Admin.create(email: current_user.email,
                             user_id: current_user.id)
      end
      @group.admin_email = admin.email
      @group.admin_id = admin.id
    else
      # Esto no tiene sentido que pase (si el usuario no existe entonces como
      # podemos estar logueados?) pero por si acaso...
      flash[:danger] = "ERROR: el usuario #{current_user.name} no existe"
    end

    if @group.save
      flash[:success] = "Grupo creado con exito!"
      redirect_to @group and return
    else
      render "new"
    end
  end

  def update
  end

  def destroy
    @group.destroy
    redirect_to root_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :max_participants_allowed,
                                  :min_gift_price, :max_gift_price)
  end

  def find_group
    begin
      @group = Group.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:danger] = "El grupo no existe"
      redirect_to groups_url and return
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_group.html.erb
<li>
  <%= link_to "#{group.name}", group %>
</li>

app/views/groups/home.html.erb
<h1>Groups#home</h1>
<p>Find me in app/views/groups/home.html.erb</p>

app/views/groups/index.html.erb
<% provide(:title, 'Grupos') %>
<h1>Listado de grupos</h1>

<% @groups.each do |g| %>
	<ul class="list-group">
		<li class="list-group-item d-flex justify-content-between align-items-center">
			<%= link_to g.name, g %>
			<span class="badge badge-primary badge-pill"><%= g.participates.count %> / <%= g.max_participants_allowed %></span>
		</li>
<% end %>

app/views/groups/new.html.erb
<% provide(:title, "Crear nuevo grupo") %>
<h1>Crear grupo</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@group) do |f| %>
			<%= render 'shared/error_messages' %>

			<%= f.label :name, "Nombre del grupo" %>
			<%= f.text_field :name, class: 'form-control' %>

			<%= f.label :max_participants_allowed, "Maximo numero de participantes" %>
			<%= f.number_field :max_participants_allowed, class: 'form-control' %>

			<p>Rango de precios (opcionales ambos)</p>
			<%= f.label :min_gift_price, "Precio minimo" %>
			<%= f.number_field :min_gift_price, class: 'form-control' %>

			<%= f.label :max_gift_price, "Precio maximo" %>
			<%= f.number_field :max_gift_price, class: 'form-control' %>

			<%= f.submit "Crear grupo", class: 'btn btn-primary' %>
		<% end %>
	</div>
</div>

app/views/groups/show.html.erb
<% provide(:title, @group.name) %>
<h1><%= @group.name %></h1>

<div class="card">
	<h4 class="card-header">Datos del grupo</h4>
	<div class="card-body">
		<p class="card-text">Creado el <%= @group.created_at.to_s(:concise) %></p>
		<p class="card-text">Minimo de precio: <%= @group.min_gift_price %></p>
		<p class="card-text">Maximo de precio: <%= @group.max_gift_price %></p>
		<p class="card-text">Maximo de integrantes: <%= @group.max_participants_allowed %></p>
		<% admin = User.find_by(email: @group.admin_email) %>
		<p class="card-text">Administrador: <%= link_to "#{admin.name} #{admin.lastname}", user_path(@group.admin) %> <%= "(#{admin.email})" %></p>

		<!-- Muestra los intercambios concluidos -->
		<% if Exchange.exists?(group_id: @group.id) %>
			<p class="card-text">Intercambios concluidos: <%= Exchange.where('exchange_date < ?', DateTime.now).count %></p>
		<% end %>
	</div>
</div>


<!-- Muestra los integrantes del grupo -->
<div class="card">
	<h4 class="card-header">Integrantes (<%= @group.participates.count %> de <%= @group.max_participants_allowed %>)</h4>
	<div class="card-body">
		<% @participants.each do |p| %>
			<p class="card-text"><%= p.participant.user.name %> <%= p.participant.user.lastname %></p>
		<% end %>
	</div>
</div>

<!-- Si el usuario no es un participante de este grupo, muestra el link de unirse -->
<% if !current_user.participant || !current_user.participant.participates.exists?(group_id: @group.id, participant_id: current_user.participant.id) %>

	<!-- Muestra el link de unirse al grupo, si no es el admin -->
	<% if !current_user.is_admin_of(@group) && @group.has_free_space %>
		<%= link_to 'Unirse al grupo', new_participate_url(@group), class: 'btn btn-info' %>
	<% end %>
<% end %>

<!-- ARREGLAR: Posiblemente mover esta logica al exchanges_controller, o groups_controller -->
<!-- Si el usuario es el administrador y no hay intercambios pendientes, muestra el link de hacer intercambio -->
<% if current_user.is_admin_of(@group) %>

	<!-- Si no hay otro intercambio pendiente (un intercambio mayor a la fecha actual) muestra el link para hacer uno -->
	<% if @group.doesnt_has_pending_exchanges %>
		<%= link_to 'Hacer sorteo', new_exchange_path(@group), params.merge(groupid: @group.id) %>
	<% else %>

		<!-- Ya hay un intercambio organizado -->
		<p>Proximo intercambio organizado:</p>
			<ul>
			<% @group.exchanges.each do |e| %>
				<li>
					<p>Fecha: <%= e.exchange_date %>, Lugar: <%= e.place %></p>
					<% if current_user.is_admin_of(@group) %>

						<div id="modalCancelarIntercambio" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLiveLabel" aria-hidden="true">
							<div class="modal-dialog" role="document">
								<div class="modal-content">
									<div class="modal-header">
										<h5 class="modal-title" id="exampleModalLiveLabel">Eliminar grupo</h5>
										<button type="button" class="close" data-dismiss="modal" aria-label="Close">
											<span aria-hidden="true">&times;</span>
										</button>
									</div>
									<div class="modal-body">
										<p>Estas seguro que deseas cancelar el intercambio?</p>
									</div>
									<div class="modal-footer">
										<button type="button" class="btn btn-secondary" data-dismiss="modal">No, olvidalo</button>
										<%= link_to "Si, estoy seguro", exchange_path(e), method: :delete, class: 'btn btn-danger' %>
									</div>
								</div>
							</div>
						</div>

						<div class="bd-example">
							<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modalCancelarIntercambio">
								Cancelar intercambio
							</button>
						</div>
					<% end %>
				</li>
			<% end %>
			</ul>
	<% end %>
<% end %>

<!-- Si el usuario actual no es el administrador del grupo y participa en el,
muestra el link para abandonar el grupo -->
<% if !current_user.is_admin_of(@group) && current_user.participates_in(@group) %>
	<div id="modalAbandonarGrupo" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLiveLabel" aria-hidden="true">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="exampleModalLiveLabel">Eliminar grupo</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body">
					<p>Estas seguro que deseas abandonar <%= @group.name %>?</p>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
					<%= link_to "Si, estoy seguro",
											leave_group_path(current_user.participant.participates.where(group_id: @group.id).first.id),
											method: :delete, class: 'btn btn-danger' %>
				</div>
			</div>
		</div>
	</div>

	<div class="bd-example">
		<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modalAbandonarGrupo">
			Abandonar grupo
		</button>
	</div>
<% end %>

<!-- Eliminar grupo -->
<% if current_user.is_admin_of(@group) %>
	<div id="modalEliminarGrupo" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLiveLabel" aria-hidden="true">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="exampleModalLiveLabel">Eliminar grupo</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body">
					<p>Estas seguro? Esto cancelara todos los nuevos intercambios</p>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
					<%= link_to "Si, quiero eliminar este grupo", group_path(@group), method: :delete, class: 'btn btn-danger' %>
				</div>
			</div>
		</div>
	</div>

	<div class="bd-example">
		<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modalEliminarGrupo">
			Eliminar grupo
		</button>
	</div>
<% end %>