config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  get "/perfil/:id", to: "users#show", as: "profile"

  get "participates/new/:groupid", to: "participates#new", as: "new_participate"
  post "participates/new/:groupid", to: "participates#create", as: "create_participate"
  delete "participates/:id", to: "participates#destroy", as: "leave_group"

  get "exchanges/new/:groupid", to: "exchanges#new", as: "new_exchange"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  get "groups/home"
  get "groups/index"

  get "shops/index"
  get "shops/show"

  resources :users
  resources :groups
  resources :exchanges
  resources :shops
  resources :give

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
# Relacion Administrador en el modelo logico
class Admin < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  belongs_to :user
  has_many :groups, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buy.rb
# Relacion Compra en el modelo logico
class Buy < ApplicationRecord
  validates :participant_id, presence: true
  validates :gift_id, presence: true
  belongs_to :participant
  belongs_to :gift
end

app/models/exchange.rb
# Relacion Intercambio en el modelo logico
class Exchange < ApplicationRecord
  validates :exchange_date, presence: true
  validates :group_id, presence: true
  validates :place, presence: true
  belongs_to :group

  has_many :give, dependent: :destroy
end

app/models/gift.rb
# Relacion Regalo en el modelo logico
class Gift < ApplicationRecord
  validates :code, presence: true
  validates :name, :price, :description, presence: true
  belongs_to :shop
end

app/models/give.rb
# Relacion Regala en el modelo logico
class Give < ApplicationRecord
  validates :giver_id, presence: true
  validates :receiver_id, presence: true
  validates :exchange_id, presence: true
  belongs_to :giver, class_name: "User"
  belongs_to :receiver, class_name: "User"
end

app/models/group.rb
# Relacion Grupo en el modelo logico
class Group < ApplicationRecord
  validates :name, presence: true
  validates :max_participants_allowed, presence: true
  validates :admin_email, presence: true
  validates :admin_id, presence: true
  belongs_to :admin

  has_many :participates, dependent: :destroy
  has_many :exchanges, dependent: :destroy

  # Retorna true si el grupo tiene espacio para otro participante, false si no
  def has_free_space
    self.participates.count < self.max_participants_allowed
  end

  # Retorna true si el grupo no tiene intercambios pendientes, false si no
  def doesnt_has_pending_exchanges
    Exchange.where(["group_id = ? and exchange_date >= ?", self.id, Time.now])
      .order(exchange_date: :desc)
      .empty?
  end
end

app/models/like.rb
# Relacion Gustos en el modelo logico
class Like < ApplicationRecord
  validates :user_id, presence: true
  validates :user_like, presence: true
  belongs_to :user
end

app/models/participant.rb
# Relacion Participante en el modelo logico
class Participant < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  belongs_to :user
  has_many :participates, dependent: :destroy
end

app/models/participate.rb
# Relacion Participa en el modelo logico
class Participate < ApplicationRecord
  validates :participant_id, presence: true
  validates :group_id, presence: true
  belongs_to :participant
  belongs_to :group

  has_many :wishes, dependent: :destroy
  accepts_nested_attributes_for :wishes, allow_destroy: true, reject_if: :all_blank
end

app/models/shop.rb
# Relacion Tienda en el modelo logico
class Shop < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true, uniqueness: true
  has_many :gifts
end

app/models/user.rb
# Relacion Usuario en el modelo logico
class User < ApplicationRecord

  # Regex para validar el formato del email.
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
                    length: { maximum: 255 },
                    uniqueness: { case_sensitive: false }, # Al hacerlo asi, uniqueness = true
                    format: { with: VALID_EMAIL_REGEX }

  # Valida que el usuario tenga nombre, apellido y edad
  validates :name, presence: true
  validates :lastname, presence: true

  # Valida que el usuario tenga una password, con longitud minima 6 (arbitrario)
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # El usuario solo puede estar una vez en la tabla admins
  has_one :admin, dependent: :destroy
  # El usuario solo puede estar una vez en la tabla participants
  has_one :participant, dependent: :destroy

  has_many :likes, dependent: :destroy
  accepts_nested_attributes_for :likes, allow_destroy: true

  # Antes de guardar un usuario en BD, convierte su email a minusculas
  before_save :downcase_email

  has_secure_password

  # Retorna el hash digest del string. Solo lo usamos para crear el password_digest
  # en fixtures/users.yml
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
      BCrypt::Engine.cost

    BCrypt::Password.create(string, cost: cost)
  end

  # Retorna true si el usuario es el admin del grupo, false si no
  def is_admin_of(group)
    self.email == group.admin_email
  end

  # Retorna true si el usuario es administrador de algun grupo, no importa cual. False si no
  def is_admin?
    Admin.exists? user_id: self.id
  end

  # Retorna true si el usuario es participante de algun grupo, no importa cual. False si no
  def is_participant?
    Participant.exists? user_id: self.id
  end

  # Retorna true si el usuario participa en el grupo, false si no
  def participates_in(group)
    self.participant && self.participant.participates && self.participant.participates.exists?(group_id: group.id, participant_id: self.participant.id)
  end

  # Retorna la edad del usuario
  def age
    now = Time.now.utc.to_date
    dob = self.birthday
    now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
  end

  private

  # Convierte en minusculas el email del usuario
  def downcase_email
    email.downcase!
  end
end

app/models/wish.rb
class Wish < ApplicationRecord
  validates :participant_wish, presence: true
  belongs_to :participate
end

app/helpers/exchanges_helper.rb
module ExchangesHelper
end

app/helpers/give_helper.rb
module GiveHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logea al usuario
  def log_in(user)
    # Coloca una cookie temporal en el navegador, con la id el usuario
    # encriptada
    session[:user_id] = user.id
  end

  # Retorna true si el usuario actual es el usuario especificado
  def current_user?(user)
    user == current_user
  end

  # Cierra la sesion del usuario actual
  def log_out
    session.delete :user_id
    @current_user = nil
  end

  # Retorna el usuario actual logueado, si es que hay uno
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size: 160)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		Pagina de Amigo secreto - Base de datos 2
	</small>
</footer>

app/views/layouts/_header.html.erb
<header>
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark" id="mainNav">
  <%= link_to "Amigo secreto", root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse"
          data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
          aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto justify-content-right">

      <% if logged_in?  %>
        <li class="nav-item">
          <%= link_to "Inicio", current_user, class: 'nav-link' %>
        </li>

        <li class="nav-item">
          <%= link_to "Usuarios", users_path, class: 'nav-link' %>
        </li>

        <li class="nav-item">
          <%= link_to "Grupos", groups_path, class: 'nav-link' %>
        </li>

        <li class="nav-item">
          <%= link_to "Tiendas", shops_path, class: 'nav-link' %>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Opciones
          </a>

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Crear grupo", new_group_path, class: 'dropdown-item' %>
            <%= link_to "Perfil", current_user, class: 'dropdown-item' %>
            <%= link_to "Editar perfil", edit_user_path(current_user), class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <%= link_to "Cerrar sesion", logout_path, class: 'dropdown-item', method: :delete %>
          </div>

        </li>
      <% end %>

    </ul>
  </div>
</nav>
</header><br/><br/>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
		<title><%= full_title(yield(:title)) %></title>
		<%= render 'layouts/rails_default' %>

  </head>

  <body>
		<%= render 'layouts/header' %>

		<div class="container">
			<% flash.each do |message_type, message| %>
				<%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
			<% end %>

			<%= yield %>
			<%= render 'layouts/footer' %>
		</div>
  </body>
</html>

app/views/pages/home.html.erb
<% provide(:title, 'Principal') %>

<div class="jumbotron jumbotron-fluid">
  <div class="img"></div>
  <div class="container">
    <h1 class="display-1">Amigo secreto</h1>
    <p class="lead text-center">Donde los mejores grupos y amigos se reunen para hacer intercambios de regalos.</p>

    <div class="text-center">
      <%= link_to 'Iniciar sesion', login_path, class: 'btn btn-primary btn-xl text-uppercase text-center' %>
      <%= link_to 'Nuevo? Registrate!', new_user_path, class: 'btn btn-primary btn-xl text-uppercase text-center' %>
    </div>

  </div>
</div><br/><br/><br/><br/>

    <!-- Servicios -->
    <section id="services">
      <div class="container">

        <div class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading text-uppercase">Servicio</h2>
            <h3 class="section-subheading text-muted">Ofrecemos servicio a diversos usuarios, grupos y tiendas, para poder organizar los eventos mas memorables.</h3>
          </div>
        </div>
        <div class="row text-center">

          <div class="col-md-4">
            <span class="fa-stack fa-4x">
              <i class="fa fa-circle fa-stack-2x text-primary"></i>
              <i class="fa fa-user-circle-o fa-stack-1x fa-inverse"></i>
            </span>
            <h4 class="service-heading">Usuarios</h4>
            <p class="text-muted">Cualquiera es bienvenido a unirse. Podras
              recibir los mejores regalos de quien menos lo esperas! </p>
          </div>

          <div class="col-md-4">
            <span class="fa-stack fa-4x">
              <i class="fa fa-circle fa-stack-2x text-primary"></i>
              <i class="fa fa-users fa-stack-1x fa-inverse"></i>
            </span>
            <h4 class="service-heading">Grupos</h4>
            <p class="text-muted">Crea tus propios grupos, o unete a otros. Podras organizar o participar en intercambios con personas que quizas
            no conocias, y llevarte una buena sorpresa. </p>
          </div>

          <div class="col-md-4">
            <span class="fa-stack fa-4x">
              <i class="fa fa-circle fa-stack-2x text-primary"></i>
              <i class="fa fa-shopping-bag fa-stack-1x fa-inverse"></i>
            </span>
            <h4 class="service-heading">Tiendas</h4>
            <p class="text-muted">Especifica los regalos que quieres para los
              intercambios en los que participas, o dejalo que sea una sorpresa!</p>
          </div>

        </div>
      </div>
    </section>

    <section class="bg-light" id="portfolio">

      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading text-uppercase">Tiendas afiliadas</h2>
            <h3 class="section-subheading text-muted">Conoce que comercios estan afiliados a nuestros servicios.</h3>
          </div>
        </div>

        <div class="row">
          <div class="col-md-4 col-sm-6 portfolio-item">
            <a class="portfolio-link" data-toggle="modal" href="#portfolioModal1">
              <div class="portfolio-hover">
                <div class="portfolio-hover-content">
                  <i class="fa fa-plus fa-3x"></i>
                </div>
              </div>
              <img class="img-fluid" src="/assets/shop1.jpg" alt="">
            </a>
            <div class="portfolio-caption">
              <h4>Kyoto</h4>
              <p class="text-muted">Ropa y zapatos deportivos</p>
            </div>
          </div>

          <div class="col-md-4 col-sm-6 portfolio-item">
            <a class="portfolio-link" data-toggle="modal" href="#portfolioModal2">
              <div class="portfolio-hover">
                <div class="portfolio-hover-content">
                  <i class="fa fa-plus fa-3x"></i>
                </div>
              </div>
              <img class="img-fluid" src="/assets/shop2.jpg" alt="">
            </a>
            <div class="portfolio-caption">
              <h4>Adidas</h4>
              <p class="text-muted">Ropa deportiva</p>
            </div>
          </div>

          <div class="col-md-4 col-sm-6 portfolio-item">
            <a class="portfolio-link" data-toggle="modal" href="#portfolioModal3">
              <div class="portfolio-hover">
                <div class="portfolio-hover-content">
                  <i class="fa fa-plus fa-3x"></i>
                </div>
              </div>
              <img class="img-fluid" src="/assets/shop3.jpg" alt="">
            </a>
            <div class="portfolio-caption">
              <h4>Tony Romas</h4>
              <p class="text-muted">Restaurante de excelente calidad</p>
            </div>
          </div>

          <div class="col-md-4 col-sm-6 portfolio-item">
            <a class="portfolio-link" data-toggle="modal" href="#portfolioModal4">
              <div class="portfolio-hover">
                <div class="portfolio-hover-content">
                  <i class="fa fa-plus fa-3x"></i>
                </div>
              </div>
              <img class="img-fluid" src="/assets/shop4.jpg" alt="">
            </a>
            <div class="portfolio-caption">
              <h4>Todo electronica</h4>
              <p class="text-muted">Necesitas una resistencia, capacitor,
                LED? Viniste al lugar correcto</p>
            </div>
          </div>

          <div class="col-md-4 col-sm-6 portfolio-item">
            <a class="portfolio-link" data-toggle="modal" href="#portfolioModal5">
              <div class="portfolio-hover">
                <div class="portfolio-hover-content">
                  <i class="fa fa-plus fa-3x"></i>
                </div>
              </div>
              <img class="img-fluid" src="/assets/shop5.jpg" alt="">
            </a>
            <div class="portfolio-caption">
              <h4>Tattoo</h4>
              <p class="text-muted">Diversos articulos de culturas subversivas juveniles</p>
            </div>
          </div>

          <div class="col-md-4 col-sm-6 portfolio-item">
            <a class="portfolio-link" data-toggle="modal" href="#portfolioModal6">
              <div class="portfolio-hover">
                <div class="portfolio-hover-content">
                  <i class="fa fa-plus fa-3x"></i>
                </div>
              </div>
              <img class="img-fluid" src="/assets/shop6.jpg" alt="">
            </a>
            <div class="portfolio-caption">
              <h4>Libreria latina</h4>
              <p class="text-muted">Libros de cuentos, novelas, tecnicos, musica</p>
            </div>
          </div>

        </div>
      </div>
    </section>

app/views/shared/_error_messages.html.erb
<% if @user && @user.errors.any? %>
	<div class="error_explanation">
		<div class="alert alert-danger">
			Se han encontrado <%= pluralize(@user.errors.count, "error") %>.
		</div>
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
				<li> <%= msg %> </li>
			<% end %>
		</ul>
	</div>
<% end %>

<% if @group && @group.errors.any? %>
	<div class="error_explanation">
		<div class="alert alert-danger">
			Se han encontrado <%= pluralize(@group.errors.count, "error") %>.
		</div>
		<ul>
			<% @group.errors.full_messages.each do |msg| %>
				<li> <%= msg %> </li>
			<% end %>
		</ul>
	</div>
<% end %>

<% if @participate && @participate.errors.any? %>
	<div class="error_explanation">
		<div class="alert alert-danger">
			Se han encontrado <%= pluralize(@participate.errors.count, "error") %>.
		</div>
		<ul>
			<% @participate.errors.full_messages.each do |msg| %>
				<li> <%= msg %> </li>
			<% end %>
		</ul>
	</div>
<% end %>